### ISSUE TITLE
[TODO] 심각도 낮음

### ISSUE THREAD

**Issue by miniron-v** [pknu-wap/2024-1-Game-2-Team#76]
## ⚙️ 기능 설명

위험도는 낮지만 고쳐야 하는 소소한 기능, 버그들을 적어두는 공간입니다.
(자꾸 까먹어서...)

## 📚 할 일 목록

- [x] 덱/묘지 아이콘 앵커 변경 -> 앵커가 아니었다!
- [x] 배경 음악 추가
- [x] 카드를 클릭하고 마우스가 카드 위에 있는 상태에서 손을 떼면 카드가 중앙에 고정되는 버그
- [x] Enemy가 Tutorial의 버튼을 가리는 에러. 범위 문제인 듯
- [x] 적을 모두 죽여도 끝나지 않는 에러
- [x] 튜토리얼 씬 꾸미기 (책상 배경, 페이지 그림 넣기)
- [x] 카드 추가하기 <- 새 일러 올라올 때마다 껐다 켤 예정
- [x] 디버프 아이콘 추가
- [x] 덱에 카드 추가 후 덱 UI 갱신
- [x] 씬 간 클릭 간섭 막기
- [x] 주인공 체력바 갱신 안 됨
- [x] 스토리 씬에서 주인공 체력바를 Update로 사용 중, 함수 호출로 변경
- [x] 배틀 시작 시 초기화 안 되는 오류
- [x] 프로젝트 정보 변경
- [x] 리워드 카드 계속 커져 있음
- [x] 전투 끝난 후 이전 대사 유지됨
- [x] 디버프 일부 적에게만 적용
- [x] 아이템, 카드 획득 후 알림
- [x] 적 체력바 이미지 변경
- [x] 적 체력 0 이하로 떨어지지 않게 변경
- [x] 텍스트 라인 간격 넓히기(적 행동 텍스트)
- [x] 덱이 모자랄 때 글러트니 사용 시 패가 버려짐
- [x] 전투 돌입 시 체력이 100이 됨
- [x] 스페이스바로 핸드가 버려짐
- [x] 덱 인벤에서 카드가 정렬되서 표시되도록
- [x] 화살표 몸통에 랜덤한 회전 주기
- [x] 덱 리셋 딜레이 줄이기
- [x] 정육점 이벤트 안 끝나는 버그 있음 SO 수정 필요
- [x] 전투 씬에 옵션 버튼 추가
- [x] 스토리 크리에이터에 인카니지 시리즈 추가
- [x] 잭, K, 경비원 등 적 프리팹 추가
- [x] K에 의문의 남자 할당 / 생성
- [x] 잭 일러스트 추가
- [x] 음량 뮤트 -> 저장 -> 언뮤트 시 볼륨이 돌아오지 않음
- [x] 플레이어, 적 Buff Panel 프리팹 분리 -> 캔버스가 달라 같은 프리팹도 크기가 다름
![image](https://github.com/user-attachments/assets/b4bfae10-c443-4366-aeca-7a5c03ddfbb4)
- [x] 끊어야겠지?
- [x] 선택지로 Relation이 아닌 곳으로 이동하면 효과음 재생됨
- [x] 인카니지 메인 스토리 중 일러스트가 빠진 부분이 있음
- [x] 엔딩 소리 하나 더 비교, 배틀 소리 찾기
![image](https://github.com/user-attachments/assets/0f981e56-de5c-4b2a-8798-9e25ce50c54d)
- [x] 이거 해결
- [x] 튜토 이벤 첨삭
  - [x] 다이어리
  - [x] 직업 이벤트
- [ ] 실드 이펙트가 특정 해상도에서 비정상적으로 출력됨
- [x] 전투 종료 또는 시작 시 디버프 초기화 안 됨
- [ ] 영장 발부 후 코스트 색이 변하지 않는 에러
  - [ ] 이거 고치려면 카드 풀링 대충 만들어진 걸 뜯어 고쳐야 한다....
- [x] 침묵 스택과 침묵 아이콘 구별
- [x] 정화 아이콘 추가

## 💬 코멘트

다른 분들도 여기 기록용으로 쓰세요~~~

**Comment by miniron-v** [comment]
값 복사 안 하고 원본 가져온 게 문제였다니... (턴 종료 시 모든 적에게 버프/디버프 적용할 때)
